# Generated by Django 5.0.7 on 2024-08-04 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.BooleanField(default=False, verbose_name='Чтение')),
                ('updating', models.BooleanField(default=False, verbose_name='Обновление')),
                ('deleting', models.BooleanField(default=False, verbose_name='Удаление')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ пользователя к задаче',
                'verbose_name_plural': 'Доступы пользователей к задачам',
                'unique_together': {('user', 'todo')},
            },
        ),
    ]
